---
# Meta information for prometheus-node-exporter role

galaxy_info:
  author: Ansible Admin
  description: Install and configure Prometheus Node Exporter
  company: Local
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - monitoring
    - prometheus
    - metrics

dependencies: []