# Backup configuration for automation stack

- name: Detect system architecture for rclone
  ansible.builtin.set_fact:
    rclone_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'arm' }}"

- name: Install rclone
  ansible.builtin.get_url:
    url: "https://downloads.rclone.org/v{{ rclone_version | default('1.63.1') }}/rclone-v{{ rclone_version | default('1.63.1') }}-linux-{{ rclone_arch }}.zip"
    dest: "/tmp/rclone.zip"
  register: rclone_download

- name: Extract rclone
  ansible.builtin.unarchive:
    src: "/tmp/rclone.zip"
    dest: "/tmp"
    remote_src: true
  when: rclone_download.changed

- name: Install rclone binary
  ansible.builtin.copy:
    src: "/tmp/rclone-v{{ rclone_version | default('1.63.1') }}-linux-{{ rclone_arch }}/rclone"
    dest: "/usr/local/bin/rclone"
    mode: '0755'
    remote_src: true
  become: true
  when: rclone_download.changed

- name: Create rclone config directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/rclone"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: Create rclone configuration
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "/home/{{ ansible_user }}/.config/rclone/rclone.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Create backup directory
  ansible.builtin.file:
    path: "{{ automation_data_path }}/backups"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create backup script
  ansible.builtin.template:
    src: backup-automation.sh.j2
    dest: "{{ automation_stack_home }}/scripts/backup-automation.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create backup restoration script
  ansible.builtin.template:
    src: restore-automation.sh.j2
    dest: "{{ automation_stack_home }}/scripts/restore-automation.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create cron job for automated backups
  ansible.builtin.cron:
    name: "Automation stack backup"
    minute: "0"
    hour: "3"
    job: "{{ automation_stack_home }}/scripts/backup-automation.sh >> {{ automation_stack_home }}/logs/backup.log 2>&1"
    user: "{{ ansible_user }}"
  when: backup_enabled | default(true)

- name: Create backup cleanup cron job
  ansible.builtin.cron:
    name: "Cleanup old backups"
    minute: "30"
    hour: "3"
    job: "find {{ automation_data_path }}/backups -name '*.tar.gz' -mtime +{{ backup_retention_days | default(30) }} -delete"
    user: "{{ ansible_user }}"
  when: backup_enabled | default(true)

