- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags: [packages]

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ automation_base_packages }}"
    state: present
  become: true
  tags: [packages]

- name: Include storage setup
  ansible.builtin.include_tasks: storage.yml
  tags: [storage]

- name: Include Docker setup
  ansible.builtin.include_tasks: docker.yml
  tags: [docker]

- name: Include Traefik setup
  ansible.builtin.include_tasks: traefik.yml
  when: services_enabled.traefik | default(true)
  tags: [traefik, reverse-proxy]

- name: Include stack deployment
  ansible.builtin.include_tasks: stack.yml
  tags: [stack, deploy]

- name: Include backup configuration
  ansible.builtin.include_tasks: backup.yml
  when: backup_enabled | default(true)
  tags: [backup]

- name: Configure firewall rules for automation stack
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    comment: "Automation stack service"
  loop:
    - "{{ traefik_web_port }}"
    - "{{ traefik_websecure_port }}"
    - "{{ traefik_dashboard_port }}"
  become: true
  tags: [firewall, security]

- name: Create systemd service for auto-start
  ansible.builtin.template:
    src: automation-stack.service.j2
    dest: /etc/systemd/system/automation-stack.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart automation stack
  tags: [systemd, auto-start]

- name: Enable automation stack service for auto-start
  ansible.builtin.systemd:
    name: automation-stack
    enabled: true
    daemon_reload: true
  become: true
  tags: [systemd, auto-start]

