# Traefik reverse proxy setup

- name: Create Traefik configuration directory
  ansible.builtin.file:
    path: "{{ automation_stack_home }}/config/traefik"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create Traefik data directory
  ansible.builtin.file:
    path: "{{ automation_data_path }}/traefik"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create acme.json file for Let's Encrypt certificates
  ansible.builtin.file:
    path: "{{ automation_data_path }}/traefik/acme.json"
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Create Traefik static configuration
  ansible.builtin.template:
    src: traefik-static.yml.j2
    dest: "{{ automation_stack_home }}/config/traefik/traefik.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  notify: restart automation stack

- name: Create Traefik dynamic configuration
  ansible.builtin.template:
    src: traefik-dynamic.yml.j2
    dest: "{{ automation_stack_home }}/config/traefik/dynamic.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  notify: restart automation stack

- name: Create Traefik dynamic configuration
  ansible.builtin.template:
    src: traefik-dynamic.yml.j2
    dest: "{{ automation_stack_home }}/config/traefik/dynamic.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  notify: restart automation stack

