---
# Handlers for prometheus-exporters role
# Note: reload systemd uses common handler

- name: Restart node-exporter
  ansible.builtin.systemd:
    name: Node-exporter
    state: restarted
  become: true
  when: node_exporter_enabled

- name: Restart pihole-exporter
  ansible.builtin.systemd:
    name: Pihole-exporter
    state: restarted
  become: true
  when: pihole_exporter_enabled

- name: Restart pi-hardware-metrics
  ansible.builtin.systemd:
    name: Pi-hardware-metrics.service
    state: restarted
  become: true
  when: pi_hardware_metrics_enabled

- name: Restart pi-hardware-metrics-timer
  ansible.builtin.systemd:
    name: Pi-hardware-metrics.timer
    state: restarted
    enabled: true
  become: true
  when: pi_hardware_metrics_enabled

- name: Restart docker-metrics
  ansible.builtin.systemd:
    name: Docker-metrics.service
    state: restarted
  become: true
  when: docker_exporter_enabled

- name: Restart docker-metrics-timer
  ansible.builtin.systemd:
    name: Docker-metrics.timer
    state: restarted
    enabled: true
  become: true
  when: docker_exporter_enabled

# restart docker uses common handler
