---
# Handlers for music-stack role

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true

- name: restart music stack
  community.docker.docker_compose_v2:
    project_src: "{{ music_stack_home }}"
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true