---
- name: Converge - Hardware detection
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Include detect_hardware task
      ansible.builtin.include_role:
        name: Common
        tasks_from: detect_hardware
