---
role_name_check: 0
driver:
  name: podman
platforms:
  - name: Debian12-network
    image: ${MOLECULE_IMAGE:-docker.io/geerlingguy/docker-debian12-ansible:latest}
    pre_build_image: true
    command: ${MOLECULE_COMMAND:-/lib/systemd/systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        timezone: UTC
verifier:
  name: ansible
scenario:
  name: network-facts
  description: Test network facts detection and CIDR calculation
