---
- name: Restart pihole-FTL
  ansible.builtin.set_fact:
    service_name: "pihole-FTL"
  notify: restart systemd service

- name: Reload pihole
  ansible.builtin.shell: pihole restartdns
  become: true

- name: Restart pihole-exporter
  ansible.builtin.set_fact:
    service_name: "pihole-exporter"
  notify: restart systemd service

- name: Restart chrony
  ansible.builtin.set_fact:
    service_name: "chrony"
  notify: restart systemd service

- name: Rollback pihole
  block:
    - name: Stop Pi-hole service
      ansible.builtin.systemd:
        name: Pihole-FTL
        state: stopped
      become: true
      ignore_errors: true

    - name: Restore configuration from backup if available
      ansible.builtin.shell: |
        if [ -d "/etc/pihole.backup" ]; then
          rm -rf /etc/pihole
          mv /etc/pihole.backup /etc/pihole
        fi
      become: true
      ignore_errors: true

    - name: Start Pi-hole service
      ansible.builtin.systemd:
        name: Pihole-FTL
        state: started
      become: true
      ignore_errors: true
