---
- name: Restart pihole-FTL
  ansible.builtin.systemd:
    name: pihole-FTL
    state: restarted
    enabled: true
  become: true

- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
    enabled: true
  become: true
