---
driver:
  name: podman

platforms:
  - name: test
    hostname: false
    image: ${MOLECULE_IMAGE:-docker.io/geerlingguy/docker-debian12-ansible:latest}
    command: ${MOLECULE_COMMAND:-/lib/systemd/systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: ansible
