---
firewall_enabled: true
firewall_policy_incoming: deny
firewall_policy_outgoing: allow
firewall_policy_routed: deny

# Host-specific ports in addition to common_firewall_ports
firewall_ports: []

firewall_rules: []

firewall_logging: "low"
