---
# Firewall configuration tasks

- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes
    cache_valid_time: "{{ package_cache_valid_time | default(3600) }}"
  become: yes

- name: Reset UFW to defaults
  ufw:
    state: reset
  become: yes
  when: firewall_reset | default(false)

- name: Set UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: "{{ firewall_policy_incoming }}" }
    - { direction: outgoing, policy: "{{ firewall_policy_outgoing }}" }
    - { direction: routed, policy: "{{ firewall_policy_routed }}" }
  become: yes

- name: Configure UFW logging
  ufw:
    logging: "{{ firewall_logging }}"
  become: yes

- name: Allow SSH (always required)
  ufw:
    rule: allow
    port: "22"
    comment: "SSH access"
  become: yes

- name: Configure common firewall ports
  ufw:
    rule: allow
    port: "{{ item.port | string }}"
    comment: "{{ item.comment | default('Service port') }}"
    proto: "{{ item.proto | default('tcp') }}"
  loop: "{{ common_firewall_ports | default([]) }}"
  become: yes
  when: common_firewall_ports is defined

- name: Configure host-specific firewall ports
  ufw:
    rule: allow
    port: "{{ item | string }}"
    comment: "{{ item }} service"
  loop: "{{ firewall_ports | default([]) }}"
  become: yes
  when: firewall_ports is defined

- name: Configure advanced firewall rules
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default('tcp') }}"
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    comment: "{{ item.comment | default('Custom rule') }}"
  loop: "{{ firewall_rules | default([]) }}"
  become: yes
  when: firewall_rules is defined and firewall_rules | length > 0

- name: Enable UFW
  ufw:
    state: enabled
  become: yes
  when: firewall_enabled | default(true)