# Firewall configuration tasks

- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
    cache_valid_time: "{{ package_cache_valid_time | default(3600) }}"
  become: true

- name: Reset UFW to defaults
  community.general.ufw:
    state: reset
  become: true
  when: firewall_reset | default(false)

- name: Reload systemd and ensure UFW is available
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Set UFW default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - {direction: incoming, policy: "{{ firewall_policy_incoming }}"}
    - {direction: outgoing, policy: "{{ firewall_policy_outgoing }}"}
    - {direction: routed, policy: "{{ firewall_policy_routed }}"}
  become: true
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: Configure UFW logging
  community.general.ufw:
    logging: "{{ firewall_logging }}"
  become: true
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: Allow SSH (always required)
  community.general.ufw:
    rule: allow
    port: "22"
    comment: "SSH access"
  become: true
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: Configure common firewall ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port | string }}"
    comment: "{{ item.comment | default('Service port') }}"
    proto: "{{ item.proto | default('tcp') }}"
  loop: "{{ common_firewall_ports | default([]) }}"
  become: true
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  when: common_firewall_ports is defined and common_firewall_ports | length > 0

- name: Configure host-specific firewall ports
  community.general.ufw:
    rule: allow
    port: "{{ item | string }}"
    comment: "{{ item }} service"
  loop: "{{ firewall_ports | default([]) }}"
  become: true
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  when: firewall_ports is defined and firewall_ports | length > 0

- name: Configure advanced firewall rules
  community.general.ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default('tcp') }}"
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    comment: "{{ item.comment | default('Custom rule') }}"
  loop: "{{ firewall_rules | default([]) }}"
  become: true
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  when: firewall_rules is defined and firewall_rules | length > 0

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: true
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  when: firewall_enabled | default(true)

