---
galaxy_info:
  namespace: homelab
  role_name: os
  description: Discover and normalize the device OS and CPU architecture
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - bookworm # Debian 12
        - trixie # Debian 13

collections:
  - ansible.utils

# Safe to include first: no dependencies.
dependencies: []
