galaxy_info:
  author: Ansible Admin
  description: Automation stack for Raspberry Pi 4B with Traefik reverse proxy
  company: Local
  license: MIT
  min_ansible_version: '2.12'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - automation
    - traefik
    - docker
    - raspberry-pi
    - reverse-proxy
    - ssl

collections:
  - community.docker
  - community.general
  - ansible.posix

dependencies:
  - role: common
  - role: firewall
  - role: prometheus-node-exporter

