---
# Docker setup tasks

- name: Check if Docker is already installed
  command: docker --version
  register: docker_check
  failed_when: false
  changed_when: false

- name: Install Docker if not present
  block:
    - name: Install Docker prerequisites
      apt:
        name:
          - curl
          - ca-certificates
        state: present
        update_cache: yes
      become: yes

    - name: Download and install Docker using convenience script
      shell: |
        curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
        sh /tmp/get-docker.sh
        rm -f /tmp/get-docker.sh
      become: yes
      args:
        creates: /usr/bin/docker

  when: docker_check.rc != 0

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Install Docker Compose (standalone)
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-armv7"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: yes

- name: Create music stack directory
  file:
    path: "{{ music_stack_home }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'