---
# Docker installation and setup

- name: Install Docker prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes

- name: Remove conflicting Docker packages
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent
  become: yes

- name: Download Docker convenience script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  become: yes

- name: Install Docker using convenience script
  shell: /tmp/get-docker.sh
  become: yes
  args:
    creates: /usr/bin/docker

- name: Clean up Docker install script
  file:
    path: /tmp/get-docker.sh
    state: absent
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Install Docker Compose (standalone)
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-armv7"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: yes

- name: Create music stack directory
  file:
    path: "{{ music_stack_home }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'