---
# Music Stack setup tasks for Pi 3B

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ music_stack_base_packages }}"
    state: present
  become: true

- name: Include Docker setup
  ansible.builtin.include_tasks: docker.yml
  tags: [docker]

- name: Include SSD mounting
  ansible.builtin.include_tasks: storage.yml
  tags: [storage]

- name: Include music stack deployment
  ansible.builtin.include_tasks: stack.yml
  tags: [stack, config]

- name: Include backup configuration
  ansible.builtin.include_tasks: backup.yml
  tags: [backup]
  when: backup_enabled | default(false)

- name: Configure firewall rules for music stack
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    comment: "Music stack service"
  loop: "{{ music_stack_ports }}"
  become: true
  when: music_stack_ports is defined and music_stack_ports | length > 0