---
# SSD mounting and storage setup

- name: Install filesystem utilities
  apt:
    name:
      - parted
      - e2fsprogs
      - ntfs-3g
      - exfat-fuse
      - exfatprogs
    state: present
  become: yes

- name: Check if SSD device exists
  stat:
    path: "{{ ssd_device }}"
  register: ssd_exists

- name: Fail if SSD device not found
  fail:
    msg: "SSD device {{ ssd_device }} not found. Please connect your SSD and update the ssd_device variable."
  when: not ssd_exists.stat.exists

- name: Get SSD filesystem info
  filesystem:
    fstype: "{{ ssd_filesystem }}"
    dev: "{{ ssd_device }}"
  become: yes
  when: ssd_format | default(false)

- name: Create music library mount point
  file:
    path: "{{ music_library_path }}"
    state: directory
    mode: '0755'
  become: yes

- name: Mount SSD
  mount:
    path: "{{ music_library_path }}"
    src: "{{ ssd_device }}"
    fstype: "{{ ssd_filesystem }}"
    opts: "{{ ssd_mount_options }}"
    state: mounted
  become: yes

- name: Add SSD to fstab
  mount:
    path: "{{ music_library_path }}"
    src: "{{ ssd_device }}"
    fstype: "{{ ssd_filesystem }}"
    opts: "{{ ssd_mount_options }}"
    state: present
  become: yes

- name: Set ownership of music library
  file:
    path: "{{ music_library_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
  become: yes

- name: Create music library subdirectories
  file:
    path: "{{ music_library_path }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - music
    - downloads
    - processing
    - backups