all:
  children:
    services:
      hosts:
        pi-dns:
          ansible_host: 192.168.20.10
          ansible_user: ansible
          device_role: dns
          device_type: rpi3b
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/ansible_controller_key
