---
galaxy_info:
  author: Ansible Admin
  description: Centralized UFW firewall management
  company: Local
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - firewall
    - ufw

dependencies: []