---
# Common tasks for all hosts running Debian Bookworm

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ package_cache_valid_time | default(3600) }}"
  become: true

- name: Install essential packages
  ansible.builtin.apt:
    name: "{{ common_packages | default([]) }}"
    state: present
  become: true

- name: Configure fail2ban for SSH protection
  ansible.builtin.copy:
    content: |
      [sshd]
      enabled = {{ fail2ban_enabled | default(true) | ternary('true', 'false') }}
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = {{ fail2ban_ssh_maxretry | default(3) }}
      bantime = {{ fail2ban_ssh_bantime | default(600) }}
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart fail2ban

- name: Start and enable fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
  become: true
  when: 
    - fail2ban_enabled | default(true)
    - not ansible_check_mode

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone | default('UTC') }}"
  become: true

- name: Configure log rotation
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/system-logs
    owner: root
    group: root
    mode: '0644'
  become: true