---
# Automation server specific configuration for Raspberry Pi 4B

# Device configuration
device_type: rpi4b
device_specs:
  cpu: "ARM Cortex-A72 4-core 1.5GHz"
  memory: "4GB (1.8GB available)"
  architecture: "aarch64"

# Storage configuration
ssd_device: "/dev/sda1"
ssd_filesystem: "ext4"
ssd_mount_options: "defaults,noatime,errors=remount-ro"
ssd_format: false
automation_data_path: "/mnt/automation-data"

# Network configuration
domain_name: "{{ vault_domain_name | default('local.example.com') }}"
subdomain_traefik: "traefik"
subdomain_nextcloud: "cloud"
subdomain_paperless: "docs"

# Docker configuration
docker_compose_version: "v2.24.5"
automation_stack_home: "/home/automation/automation-stack"

# Service ports
traefik_web_port: 80
traefik_websecure_port: 443
traefik_dashboard_port: 8080
nextcloud_port: 8081
paperless_port: 8082

# Firewall configuration for automation stack
firewall_ports:
  - 22    # SSH
  - 80    # HTTP (Traefik)
  - 443   # HTTPS (Traefik)
  - 8080  # Traefik Dashboard

# SSL configuration
letsencrypt_email: "{{ vault_letsencrypt_email | default('admin@example.com') }}"
letsencrypt_staging: true  # Set to false for production certificates

# Service configuration
services_enabled:
  traefik: true
  nextcloud: true
  paperless: true

# Backup configuration
backup_enabled: true
backup_schedule: "0 3 * * *"  # Daily at 3 AM

# Additional system packages
additional_packages:
  - rsync
  - curl
  - wget
  - htop
  - ncdu
  - tree
  - unzip
  - ca-certificates

# User configuration
automation_user: automation
automation_uid: 1000
automation_gid: 1000

# Timezone
timezone: Europe/Warsaw