# Raspberry Pi 3 specific configuration

device_type: rpi3b

music_stack_enabled: true
music_stack_home: "/home/media/compose"

ssd_device: "/dev/sda1"
ssd_filesystem: "ext4"
ssd_mount_options: "defaults,noatime,errors=remount-ro"
music_library_path: "/mnt/data"
ssd_format: false

ansible_uid: 1000
ansible_gid: 1000

firewall_ports:
  - {port: 22, comment: "SSH"}
  - {port: 4545, comment: "Navidrome"}
  - {port: 9001, comment: "Portainer Agent"}
  - {port: 2376, comment: "Docker API",}

docker_log_driver: "json-file"
docker_log_max_size: "10m"
docker_log_max_file: "3"

youtube_sync_enabled: true
