---
galaxy_info:
  author: Your Name
  description: Music Stack for Raspberry Pi 3B with Navidrome, Beets, and backup synchronization
  company: 
  license: MIT
  min_ansible_version: '2.9'
  
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - music
    - media
    - navidrome
    - beets
    - docker
    - raspberry-pi

dependencies: []