---
driver:
  name: Podman

platforms:
  - name: Test
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    ansible.builtin.command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: Ansible

verifier:
  name: Ansible
