---
- name: Configure all hosts
  hosts: all
  become: yes
  roles:
    - common

- name: Configure DNS servers
  hosts: services
  become: yes
  roles:
    - role: dns
      when: device_role == "dns"

- name: Configure security services
  hosts: services
  become: yes
  roles:
    - role: security
      when: device_role == "security"