---
- name: Configure all hosts
  hosts: all
  become: yes
  roles:
    - common

- name: Configure DNS servers
  hosts: services
  become: yes
  roles:
    - dns
  when: device_role == "dns"

- name: Configure security services
  hosts: services
  become: yes
  roles:
    - security
  when: device_role == "security"