---
- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: restart ossec
  systemd:
    name: ossec
    state: restarted
  become: yes

- name: restart crowdsec
  systemd:
    name: crowdsec
    state: restarted
  become: yes

- name: restart uptime-kuma
  systemd:
    name: uptime-kuma
    state: restarted
  become: yes

- name: restart otel-collector
  systemd:
    name: otel-collector
    state: restarted
  become: yes